### PR TITLE
Added a notebook for teaching git.

### PR DESCRIPTION
**Pull request by arokem**
Materials for teaching git

### CODE REVIEW

**Comment by mrterry** [comment]
Do you have a recommendation for $EDITOR for windows users?  Does nano come with gitbash?

**Comment by arokem** [comment]
If only life were that simple:

http://stackoverflow.com/questions/10564/how-can-i-set-up-an-editor-to-work-with-git-on-windows

I am also going to shoot an email to the Tutors list to see what people
have been doing for this.

**Comment by mrterry** [comment]
_sigh_  I hate the amount of time we have to spend coming up with windows hacks and apologize for them in class.  It makes us come off as mac/linux zealots.  Unfortunately, the tooling on windows is so different.

**Comment by arokem** [comment]
And by "different" you mean "primitive", right? :-)

**Comment by mrterry** [comment]
Unhelpful and hobbyist-hostile is what I was thinking, but primitive works too : )

**Comment by vahi** [comment]
hopefully, we should have a VM for the whole bootcamp. In that case, we can have emacs and vi preinstalled in th VM.

**Comment by mrterry** [comment]
Don't get me wrong, having the VM is a great backstop.  It solves installation issues and make sure that everyone's screen looks the same.

However, I think it hinders our students ability to learn.  In addition to the material we're teaching, they also have to acclimate to a new, (very) different OS.  Cognitive load is a thing, after all.  After the workshop, they throw their VMs away and no longer have tools we've taught them, or they have to figure out how to install everything themselves.  I think it is more valuable to the students to give them tools in a context where they are familiar.

**Comment by mrterry** [comment]
For our purposes, I think SublimeText (or nano) is more appropriate text editor than vim or emacs.  We want something stupid simple.  All that power is just confusing and distracting for many of our students.

**Comment by vahi** [comment]
Ok that is fine. But you and ariel still would like us to include git and the python canpopy dependencies in there. right?

**Comment by mrterry** [comment]
Yes please.  Better backstops are better.  Thanks!

**Comment by arokem** [comment]
I have been (mostly) been using nano as an editor when teaching git. You
really don't want learning a text editor to get in the way of learning git.
On the other hand, you want them to get comfortable with the notion that
the text editor will pop up and getting used to reading the text in there
and writing commit messages in there.

For the first couple of days, the VM will serve as a fallback for when
things really don't work, but it's really preferable to have people work in
their usual work environment. We want to have them leaving the workshop
with the feeling that they are going to adopt these tools into their
day-to-day from now on.

And yes please to Canopy and git!

**Pull request merged**
